app/blueprints/authentication/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import check_password_hash, generate_password_hash
import string
import random

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    ### We never did a token in class, so I just made a random string for each token. I found this strategy online!
    token = db.Column(db.String(255), default=''.join(random.choice(string.ascii_letters) for i in range (25)))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)


    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.generate_password(self.password)

    def check_password(self, password_to_check):
        return check_password_hash(self.password, password_to_check)

    def generate_password(self, password_create_salt_from):
        self.password = generate_password_hash(password_create_salt_from)

    # def to_dict(self):
    #     data = {
    #         'id': self.id,
    #         'first_name': self.first_name,
    #         'last_name': self.last_name,
    #         'email': self.email
    #     }
    #     return data    

    # def __repr__(self):
    #     return f'<User: {self.email}>'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/blueprints/collection/models.py
from app import db
from datetime import datetime

class Character(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    description = db.Column(db.String)
    comics_appeared_in = db.Column(db.Integer)
    super_power = db.Column(db.String)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.ForeignKey('user.id'), nullable=False)

    def __repr__(self):
        return f'<Character: {self.id} {self.user_id}>'

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Just like in Derek's fakebook, this is where the ORM is established.
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # Note to self: When you make a new blueprint, make sure to register it here.
    from app.blueprints.authentication import bp as authentication
    from app.blueprints.main import bp as main
    app.register_blueprint(authentication)
    app.register_blueprint(main)

app/blueprints/authentication/__init__.py
from flask import Blueprint

bp = Blueprint('authentication', __name__, url_prefix='/authentication')

from .import models, routes

app/blueprints/authentication/routes.py
from flask_login import current_user, login_user, logout_user
from .import bp as app
from flask import render_template, redirect, url_for, request, flash
from app.blueprints.authentication.models import User
from app import db

@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email.lower()).first()
        if user is None or not user.check_password(password):
            flash('Either that was an invalid password or username. Try again. ', 'danger')
            return redirect(request.referrer)
        flash('User has successfully logged in', 'success')
        login_user(user)
        return redirect(url_for('blog.home'))
    return render_template('authentication/login.html')

    
@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        data = request.form
        user = User.query.filter_by(email=data.get('email')).first()
        if user is not None:
            flash('That user already exists', 'warning')
            return redirect(request.referrer)
        if data.get('password') != data.get('password2'):
            flash("Your passwords don't match", 'warning')
            return redirect(request.referrer)
        new_user = User(
            first_name=data.get('first_name'),
            last_name=data.get('last_name'),
            email=data.get('email'),
            password=data.get('password')
        )
        db.session.add(new_user)
        db.session.commit()
        flash('User registered successfully', 'success')
        # automatically log in user on successful registration
        login_user(new_user)
        flash('User logged in successfully', 'success')
        return redirect(url_for('blog.home'))

    return render_template('authentication/register.html')

@app.route('/logout')
def logout():
    logout_user()
    flash('User logged out successfully', 'primary')
    return redirect(url_for('authentication.login'))

app/blueprints/collection/__init__.py
from flask import Blueprint

bp = Blueprint('collection', __name__, url_prefix='/collection')

from .import models, routes

app/blueprints/collection/routes.py
from flask import flash, redirect, render_template, current_app, request, url_for
from flask_login import current_user
from app import db

from app.blueprints.collection.models import Character
from .import bp as app

@app.route('/')
def add():
    return render_template('collection/add.html')

app/templates/authentication/login.html
{% extends 'layout.html' %}

{% block content %}
<h1>Login</h1>

<hr>

<form action="{{ url_for('authentication.login') }}" method="POST">

    <div class="form-group">
        <input type="email" class="form-control" name="email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="Password" />
    </div>
    <input type="submit" value="Login" class="btn btn-info btn-block" />

</form>
{% endblock %}

app/templates/authentication/register.html
{% extends 'layout.html' %}

{% block content %}
<h1>Register</h1>

<hr>
<form action="{{ url_for('authentication.register') }}" method="POST">

    <div class="form-group">
        <input type="text" class="form-control" name="name" placeholder="Name" />
    </div>
    <div class="form-group">
        <input type="email" class="form-control" name="email" placeholder="Email" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="Password" />
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="Confirm Password" />
    </div>
    <input type="submit" value="Register" class="btn btn-info btn-block" />

</form>
{% endblock %}

app/templates/collection/add.html
{% extends 'layout.html' %}

{% block content %}
<h1>Character Search</h1>

<hr>

<form action="{{ url_for('collection.add_hero') }}" method="POST">

    <div class="form-group">
        <input type="search" class="form-control" name="name" placeholder="Character Name" />
    </div>

</form>
{% endblock %}

app/templates/collection/view.html
{% extends 'layout.html' %}

{% block content %}
<h1>Characters</h1>

<hr>
{% endblock %}

app/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <title>Heroes</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
      <header>
          <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#EE171F;">
              <a class="navbar-brand" href="">HEROES</a>
              <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                  aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
              </button>
              <ul class="navbar-nav ml-auto">
                {% if not current_user.is_authenticated %}
                <li class="nav-item"><a href="{{ url_for('authentication.login') }}" class="nav-link">Login</a></li>
                    <li class="nav-item"><a href="{{ url_for('authentication.register') }}" class="nav-link">Register</a></li>
                {% else %}
                <li class="nav-item"><a href="{{ url_for('authentication.profile') }}" class="nav-link">Profile</a></li>
                    <li class="nav-item"><a href="{{ url_for('authentication.logout') }}" class="nav-link">Logout</a></li>
                {% endif %}
            </ul>
          </nav>
      </header>
      <main>
        {% block content %}
        {% endblock %}
      </main>
      <footer>

      </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>